const getLanguage = () => {
  return [
    "english",
    "french",
    "spanish",
    "mandarin",
    "italian",
    "japanese",
    "korean",
    "german",
    "russian",
    "hindi",
    "turkish",
    "portuguese",
    "arabic",
    "tamil",
    "dutch",
    "cantonese",
    "telugu",
    "polish",
    "czech",
    "punjabi",
    "hebrew",
    "malayalam",
    "swedish",
    "danish",
    "romanian",
    "norwegian",
  ];
};
module.exports = {
  getLanguage,
};

// const languages = [
//   "English",
//   "French",
//   "Spanish",
//   "Mandarin",
//   "Italian",
//   "Japanese",
//   "Korean",
//   "German",
//   "Russian",
//   "Hindi",
//   "Turkish",
//   "Portuguese",
//   "Arabic",
//   "Tamil",
//   "Dutch",
//   "Cantonese",
//   "Telugu",
//   "Polish",
//   "Czech",
//   "Punjabi",
//   "Hebrew",
//   "Malayalam",
//   "Swedish",
//   "Danish",
//   "Romanian",
//   "Norwegian",
// ];
