const getLanguage = () => {
  return [
    "English",
    "French",
    "Spanish",
    "Mandarin",
    "Italian",
    "Japanese",
    "Korean",
    "German",
    "Russian",
    "Hindi",
    "Turkish",
    "Portuguese",
    "Arabic",
    "Tamil",
    "Dutch",
    "Cantonese",
    "Telugu",
    "Polish",
    "Czech",
    "Punjabi",
    "Hebrew",
    "Malayalam",
    "Swedish",
    "Danish",
    "Romanian",
    "Norwegian",
  ];
};
module.exports = {
  getLanguage,
};

// const languages = [
//   "English",
//   "French",
//   "Spanish",
//   "Mandarin",
//   "Italian",
//   "Japanese",
//   "Korean",
//   "German",
//   "Russian",
//   "Hindi",
//   "Turkish",
//   "Portuguese",
//   "Arabic",
//   "Tamil",
//   "Dutch",
//   "Cantonese",
//   "Telugu",
//   "Polish",
//   "Czech",
//   "Punjabi",
//   "Hebrew",
//   "Malayalam",
//   "Swedish",
//   "Danish",
//   "Romanian",
//   "Norwegian",
// ];
